import Kothu_Parotta from './fpic/Coimbatorefoodlist/Kothu_Parotta.jpg';
import Angannan_Biryani from './fpic/Coimbatorefoodlist/Angannan_Biryani.jpg';
import Coimbatore_Chicken_Wings from './fpic/Coimbatorefoodlist/Coimbatore_Chicken_Wings.jpg';
import Kozhi_Kari_Varuval from './fpic/Coimbatorefoodlist/Kozhi_Kari_Varuval.jpg';
import Arisi_Paruppu_Saadam from './fpic/Coimbatorefoodlist/Arisi_Paruppu_Saadam.jpg';
import Coimbatore_Fish_Curry from './fpic/Coimbatorefoodlist/Coimbatore_Fish_Curry.jpg';
import Kari_Dosa from './fpic/Coimbatorefoodlist/Kari_Dosa.jpg';
import Kangeyam_Nalli_Kari from './fpic/Coimbatorefoodlist/Kangeyam_Nalli_Kari.jpg';
import Kadambur_Mutton_Gravy from './fpic/Coimbatorefoodlist/Kadambur_Mutton_Gravy.jpg';
import Paniyaram from './fpic/Coimbatorefoodlist/Paniyaram.jpg';
import Murukku_Sandwich from './fpic/Coimbatorefoodlist/Murukku_Sandwich.jpg';
import Coimbatore_Halwa from './fpic/Coimbatorefoodlist/Coimbatore_Halwa.jpg';
import Thengai_Paal_Payasam from './fpic/Coimbatorefoodlist/Thengai_Paal_Payasam.jpg';
import Kambu_Koozh from './fpic/Coimbatorefoodlist/Kambu_Koozh.jpg';
import Kothamalli_Chutney from './fpic/Coimbatorefoodlist/Kothamalli_Chutney.jpg';

export const foodarr = {
  'Ariyalur': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Chengalpattu': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Chennai': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Coimbatore':[
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Cuddalore': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Dharmapuri': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Dindigul': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Erode': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Kallakurichi': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Kancheepuram': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Karur': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Kanyakumari': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Krishnagiri': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Madurai': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Mayiladuthurai': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Nagapattinam': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Namakkal': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Perambalur': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Pudukottai': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Ramanathapuram': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Ranipet': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Salem': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Sivagangai': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Tenkasi': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Thanjavur': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Theni': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Thiruvallur': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Thiruvarur': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Thoothukudi': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Tiruchirappalli': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Thirunelveli': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Tirupathur': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Tiruppur': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Tiruvannamalai': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Nilgiris': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Vellore': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Viluppuram': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ],
  'Virudhunagar': [
    { title: 'Kothu Parotta', img: Kothu_Parotta },
    { title: 'Angannan Biryani', img: Angannan_Biryani },
    { title: 'Coimbatore Chicken Wings', img: Coimbatore_Chicken_Wings },
    { title: 'Kozhi Kari Varuval (Chicken Fry)', img: Kozhi_Kari_Varuval },
    { title: 'Arisi Paruppu Saadam (Dal Rice)', img: Arisi_Paruppu_Saadam },
    { title: 'Coimbatore Fish Curry', img: Coimbatore_Fish_Curry },
    { title: 'Kari Dosa', img: Kari_Dosa },
    { title: 'Kangeyam Nalli Kari', img: Kangeyam_Nalli_Kari },
    { title: 'Kadambur Mutton Gravy', img: Kadambur_Mutton_Gravy },
    { title: 'Paniyaram', img: Paniyaram },
    { title: 'Murukku Sandwich', img: Murukku_Sandwich },
    { title: 'Coimbatore Halwa', img: Coimbatore_Halwa },
    { title: 'Thengai Paal (Coconut Milk) Payasam', img: Thengai_Paal_Payasam },
    { title: 'Kambu Koozh (Pearl Millet Porridge)', img: Kambu_Koozh },
    { title: 'Kothamalli Chutney', img: Kothamalli_Chutney }
  ]
};